---
application:
  name: "miniproject"
  project: "Code Live"
  organization: "QoveryCommunity"
routers:
- name: "main-miniproject"
  routes:
  - application_name: "miniproject"
    paths:
    - "/*"
